name: yet_another_observer
description: Need to retrofit some observers to your existing code base? This plugin can help!
version: 2.0.0
homepage: https://github.com/magnuswikhog/yet_another_observer

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  collection:

flutter:
